### PR TITLE
Better demo fixture

### PR DESCRIPTION
**Pull request by anshulxyz**
Remove the previous test data and load fixtures again
```bash
rm src/dev.db && invoke db-upgrade load-demo-fixture
```

https://user-images.githubusercontent.com/6121530/148521055-f2da857a-c8cc-492e-a889-dbb61bb260a7.mp4

### CODE REVIEW

**Review by rgaudin — CHANGES_REQUESTED** [review]
Thanks ; Please use `<pre>` nodes for Counter, as for books.
Also, there are still a lot of stuff missing:
- Languages
- Title languages
- Title Tags
- Book languages
- Book tags

**Comment by anshulxyz** [comment]
Screenshot 2022-01-11 at 4 17 37 PM

**Comment by anshulxyz** [comment]
> Thanks ; Please use `\<pre\>` nodes for Counter, as for books. Also, there are still a lot of stuff missing:
> 
> * Languages
> * Title languages
> * Title Tags
> * Book languages
> * Book tags

Done.

**Comment by anshulxyz** [comment]
> Please use <pre> nodes for Counter, as for books.

Fixing this in a different branch along with other frontend related changes. Will update this comment with the commit message when I push that.

**Comment by rgaudin** [comment]
> > Please use `\<pre\>` nodes for Counter, as for books.
> 
> Fixing this in a different branch along with other frontend related changes. Will update this comment with the commit message when I push that.

OK, we can fix that in a second PR.

**Review by rgaudin — APPROVED** [review]

**Comment by anshulxyz** [comment]
> > > Please use `\<pre\>` nodes for Counter, as for books.
> > 
> > 
> > Fixing this in a different branch along with other frontend related changes. Will update this comment with the commit message when I push that.
> 
> OK, we can fix that in a second PR.

Hi @rgaudin I have fixed this in https://github.com/openzim/cms/commit/b7d58704184f96ae4a193d3720e7647575e9bf8c

**Pull request merged**
